### PR TITLE
Change seeds to libbitcoin community servers

### PR DESCRIPTION
**Pull request by thecodefactory**

### CODE REVIEW

**Comment by lclc** [comment]
If they are all under your control that might be a bit problematic, not ?

You could still leave the others in. The more the better ?

**Comment by evoskuil** [comment]
The others are usually failing now because Core has apparently transitioned to a proprietary mechanism, as opposed to just using the address protocol. We have two different boaters now and I see no reason to rely on the few from all Core guys.

**Comment by lclc** [comment]
Ok, makes sense. Forgot that the others are actually the DNS and most of their nodes don't accept many incoming connections.

My server is currently running on libbitcoin-ch-1.roger.coffee if you'd like to add it (also available at roger.coffee, but I'll probably use the top domain for something else one day). It accepts 20 incoming connections (I could also increase that if it helps).

**Comment by thecodefactory** [comment]
Should we map mainnet4.libbitcoin.net to libbitcoin-ch-1.roger.coffee and add it in?

**Comment by evoskuil** [comment]
Yes, to the IP address. But need to upgrade it.

**Comment by thecodefactory** [comment]
@lclc When you've updated to the latest v3, let me know and I'll add it in.

**Comment by evoskuil** [comment]
And I’ll add the DNS A record if you give me the IP address.

**Comment by lclc** [comment]
@thecodefactory Updated to 3.5.

My IP is: 159.100.246.114

**Comment by evoskuil** [comment]
DNS A records added for mainnet4 and testnet4.

**Comment by evoskuil** [comment]
Please update: https://github.com/libbitcoin/libbitcoin-server/wiki/Community-Servers

**Comment by thecodefactory** [comment]
@lclc I've added your nodes on https://github.com/libbitcoin/libbitcoin-server/wiki/Community-Servers, but please review and update the 'Hosted by' sections.  Also, optionally add donation addresses.

**Comment by lclc** [comment]
Thanks @thecodefactory, i've added the missing information.

**Comment by evoskuil** [comment]
```sh
$ bx fetch-height tcp://mainnet1.libbitcoin.net:9091
514353

$ bx fetch-height tcp://mainnet2.libbitcoin.net:9091
514353

$ bx fetch-height tcp://mainnet3.libbitcoin.net:9091
514353

$ bx fetch-height tcp://mainnet4.libbitcoin.net:9091
514353

$ bx fetch-height tcp://mainnet1.libbitcoin.net:9081 "0HxgF^7dEzWu)$R^YE/q7mm0=t@o7RDUT}K.@oY@"
514353

$ bx fetch-height tcp://mainnet2.libbitcoin.net:9081 "}[YQ:ks:iKd0F1!ycPgj:4CVzfV-=jsF}x&%ff=/"
514353

$ bx fetch-height tcp://mainnet3.libbitcoin.net:9081 "f!qCf4(YHm3rp/J15Q+!l>{jz>>eUkW9}6&pc0tB"
514353

$ bx fetch-height tcp://mainnet4.libbitcoin.net:9081 "8=mvk8!F=+>$k&-.65NCPp}4e4j)<N3wk{+N!*hM"
514353

$ bx fetch-height tcp://testnet1.libbitcoin.net:19091
1288674

$ bx fetch-height tcp://testnet2.libbitcoin.net:19091
1288674

$ bx fetch-height tcp://testnet3.libbitcoin.net:19091
1288674

$ bx fetch-height tcp://testnet4.libbitcoin.net:19091
1288674

$ bx fetch-height tcp://testnet1.libbitcoin.net:19081 ")nNv4Ji=CU:}@<LOu-<QvB)b-PIh%PX[)?mH>XAl"
1288674

$ bx fetch-height tcp://testnet2.libbitcoin.net:19081 "M>dfC.16SBU&O9hA@rUWP:k]>DF=xTJ73Iw}HE0g"
1288674

$ bx fetch-height tcp://testnet3.libbitcoin.net:19081 "ZW4K2g{E>*a@n>NqZ<VeI^2ANqw.7Ub<?>UgSiNq"
1288674

$ bx fetch-height tcp://testnet4.libbitcoin.net:19081 "8=mvk8!F=+>$k&-.65NCPp}4e4j)<N3wk{+N!*hM"
1288674
```

**Comment by evoskuil** [comment]
@lclc Something tells me it might be better to use distinct server keys for the mainnet and testnet servers.

**Comment by lclc** [comment]
@evoskuil since it runs on the same machine (just different config files) I thought it doesn't matter.
The private key is in the config file which are both in the same directory. Difference is just the systemd file to start the servers with.

Or am I ignoring a potential security problem?

**Comment by evoskuil** [comment]
If you were to split themit could create a problem given a presumed much higher level of security desired for the mainnet server. Could also be a problem of perception. We’d like to keep these identities for a long time if possible. Otherwise no other issues.

**Pull request merged**
